import {
  ArrowLeft,
  ArrowRight,
  ArrowClockwise,
  BookOpen,
  Briefcase,
  CalendarBlank,
  CaretRight,
  ChartBar,
  ChatCircleDots,
  Check,
  CheckCircle,
  CloudCheck,
  Ear,
  Fire,
  FlagCheckered,
  Flower,
  GearSix,
  GraduationCap,
  House,
  Leaf,
  Lightning,
  LockKey,
  MapTrifold,
  Moon,
  PencilSimple,
  Play,
  ShoppingBag,
  Sparkle,
  SpeakerHigh,
  Sun,
  Target,
  Timer,
  Translate,
  Trophy,
  User,
  X,
  Airplane,
  MagnifyingGlass,
  Microphone,
  ShieldCheck,
  Gift,
  Heart,
} from '@phosphor-icons/react'
import type { Icon, IconWeight } from '@phosphor-icons/react'

const icons: Record<string, Icon> = {
  home: House,
  course: MapTrifold,
  characters: Translate,
  words: BookOpen,
  review: ArrowClockwise,
  profile: User,
  settings: GearSix,
  conversation: ChatCircleDots,
  target: Target,
  chart: ChartBar,
  shop: ShoppingBag,
  fire: Fire,
  flower: Flower,
  sparkle: Sparkle,
  time: Timer,
  calendar: CalendarBlank,
  check: Check,
  complete: CheckCircle,
  lock: LockKey,
  next: ArrowRight,
  back: ArrowLeft,
  chevron: CaretRight,
  close: X,
  play: Play,
  sun: Sun,
  moon: Moon,
  audio: SpeakerHigh,
  listen: Ear,
  pencil: PencilSimple,
  trophy: Trophy,
  leaf: Leaf,
  travel: Airplane,
  study: GraduationCap,
  work: Briefcase,
  flag: FlagCheckered,
  energy: Lightning,
  cloud: CloudCheck,
  search: MagnifyingGlass,
  microphone: Microphone,
  shield: ShieldCheck,
  gift: Gift,
  heart: Heart,
}

// Legacy feature data keeps its existing interface; all structural glyphs use
// the same scalable icon family in the presentation layer.
const aliases: Record<string, string> = {
  '🏠': 'home',
  '🗺️': 'course',
  '📘': 'course',
  '📚': 'words',
  '📖': 'words',
  '🔁': 'review',
  '🌸': 'flower',
  '🔥': 'fire',
  '⭐': 'sparkle',
  '✨': 'sparkle',
  '⚙️': 'settings',
  '💬': 'conversation',
  '🎯': 'target',
  '📊': 'chart',
  '📅': 'calendar',
  '📆': 'calendar',
  '🌅': 'sun',
  '⏱️': 'time',
  '⏳': 'time',
  '🔒': 'lock',
  '✓': 'check',
  '✅': 'complete',
  '✕': 'close',
  '▶': 'play',
  '●': 'play',
  '🔊': 'audio',
  '✏️': 'pencil',
  '✍️': 'pencil',
  '🏁': 'flag',
  '🛍️': 'shop',
  '🎌': 'flag',
  '✈️': 'travel',
  '💼': 'work',
  '🌱': 'leaf',
  '🛡️': 'shield',
  '🩹': 'heart',
  '🎁': 'gift',
  あ: 'characters',
  '▶️': 'play',
  '💤': 'moon',
  '🏆': 'trophy',
  '🆕': 'sparkle',
  '📌': 'target',
  '⚡': 'energy',
}

export function AppIcon({
  name,
  size = 22,
  weight = 'regular',
  className = '',
}: {
  name: string
  size?: number
  weight?: IconWeight
  className?: string
}) {
  const IconComponent = icons[aliases[name] ?? name] ?? Sparkle
  return (
    <IconComponent
      aria-hidden="true"
      focusable="false"
      size={size}
      weight={weight}
      className={`shrink-0 ${className}`}
    />
  )
}
